#k8s
ssl_dir: /etc/ssl/k8s
kubernetes_url: https://dl.k8sre.com/v1.16.4
docker_version: 18.09.9

#集群配置
apiserver_domain_name: apiserver.k8sre.com
service_ip_range: 10.64.0.0/16
pod_ip_range: 10.80.0.0/12
