---
- name: "Deploying Kubernetes High Availability Cluster with Ansible Playbook"
  hosts: etcd master node haproxy
  roles:
    - { role: 'init', tags: "init",when: "ansible_os_family == 'RedHat'" }

- name: "签发证书"
  hosts: localhost
  connection: local
  roles:
    - { role: 'cert', tags: "cert" }

- name: "配置etcd"
  hosts: etcd
  roles:
    - { role: 'etcd', tags: "install_etcd" }

- name: "配置haproxy"
  hosts: haproxy
  roles:
    - { role: 'haproxy', tags: "install_haproxy" }
    - { role: 'keepalived', tags: "install_keepalived" }

- name: "安装docker"
  hosts: master node
  roles:
    - { role: 'docker', tags: "install_docker" }

- name: "配置kubelet"
  hosts: master node
  roles:
    - { role: 'node', tags: "install_node" }


- name: "配置master"
  hosts: master
  roles:
    - { role: 'master', tags: "install_master" }

- name: "配置集群"
  hosts: kubectl
  roles:
    - { role: 'bootstrapping', tags: "bootstrapping" }



