- name: "创建ssl证书目录"
  file:
    path: "{{ ssl_dir }}"
    state: directory

- name: "Generate Etcd CA private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/etcd-ca.key"
    type: RSA
    size: 4096
- name: "Generate Etcd CA request"
  openssl_csr:
    path: "{{ ssl_dir }}/etcd-ca.csr"
    privatekey_path: "{{ ssl_dir }}/etcd-ca.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: etcd-ca
    basic_constraints_critical: yes
    basic_constraints:
      - CA:TRUE
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyCertSign
      - keyEncipherment
- name: "Generate Etcd CA certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/etcd-ca.pem"
    provider: selfsigned
    privatekey_path: "{{ ssl_dir }}/etcd-ca.key"
    csr_path: "{{ ssl_dir }}/etcd-ca.csr"

- name: "Generate Etcd Server private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/etcd-server.key"
    type: RSA
    size: 4096
- name: "Generate Etcd Server request"
  openssl_csr:
    path: "{{ ssl_dir }}/etcd-server.csr"
    privatekey_path: "{{ ssl_dir }}/etcd-server.key"
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: etcd-server
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
      - serverAuth
    subject_alt_name: "{{ item | map('regex_replace', '^', 'IP:') | list }}"
  with_list:
    - "{{ groups['master'] | union(groups['etcd']) }}"
- name: "Generate Etcd Server certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/etcd-server.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/etcd-server.key"
    csr_path: "{{ ssl_dir }}/etcd-server.csr"
    ownca_path: "{{ ssl_dir }}/etcd-ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/etcd-ca.key"

- name: "Generate Etcd Client private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/etcd-client.key"
    type: RSA
    size: 4096
- name: "Generate Etcd Client request"
  openssl_csr:
    path: "{{ ssl_dir }}/etcd-client.csr"
    privatekey_path: "{{ ssl_dir }}/etcd-client.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: system:masters
    common_name: etcd-client
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
- name: "Generate Etcd Client certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/etcd-client.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/etcd-client.key"
    csr_path: "{{ ssl_dir }}/etcd-client.csr"
    ownca_path: "{{ ssl_dir }}/etcd-ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/etcd-ca.key"

- name: "Generate Etcd Peer private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/etcd-peer.key"
    type: RSA
    size: 4096
- name: "Generate Etcd Peer request"
  openssl_csr:
    path: "{{ ssl_dir }}/etcd-peer.csr"
    privatekey_path: "{{ ssl_dir }}/etcd-peer.key"
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: etcd-peer
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
      - serverAuth
    subject_alt_name: "{{ item | map('regex_replace', '^', 'IP:') | list }}"
  with_list:
    - "{{ groups['etcd'] }}"
- name: "Generate Etcd Peer certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/etcd-peer.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/etcd-peer.key"
    csr_path: "{{ ssl_dir }}/etcd-peer.csr"
    ownca_path: "{{ ssl_dir }}/etcd-ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/etcd-ca.key"


- name: "Generate CA private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/ca.key"
    type: RSA
    size: 4096
- name: "Generate CA request"
  openssl_csr:
    path: "{{ ssl_dir }}/ca.csr"
    privatekey_path: "{{ ssl_dir }}/ca.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: kubernetes
    basic_constraints_critical: yes
    basic_constraints:
      - CA:TRUE
    key_usage_critical: yes
    key_usage:
      - cRLSign
      - keyCertSign
      - digitalSignature
      - keyEncipherment
- name: "Generate CA certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/ca.pem"
    provider: selfsigned
    privatekey_path: "{{ ssl_dir }}/ca.key"
    csr_path: "{{ ssl_dir }}/ca.csr"

- name: "Generate kubectl private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/admin.key"
    type: RSA
    size: 4096
- name: "Generate kubectl request"
  openssl_csr:
    path: "{{ ssl_dir }}/admin.csr"
    privatekey_path: "{{ ssl_dir }}/admin.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: system:masters
    common_name: admin
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
- name: "Generate kubectl certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/admin.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/admin.key"
    csr_path: "{{ ssl_dir }}/admin.csr"
    ownca_path: "{{ ssl_dir }}/ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/ca.key"

- name: "merge lists"
  set_fact:
    lists_merged: "{{ groups['master'] | union(groups['k8s_service']) | map('regex_replace', '^', 'IP:') | list }} + {{ groups['k8s_domain'] | map('regex_replace', '^', 'DNS:') | list}}"
- name: "Generate kube-apiserver private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/kube-apiserver.key"
    type: RSA
    size: 4096
- name: "Generate kube-apiserver request"
  openssl_csr:
    path: "{{ ssl_dir }}/kube-apiserver.csr"
    privatekey_path: "{{ ssl_dir }}/kube-apiserver.key"
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: kube-apiserver
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth
    subject_alt_name: "{{ lists_merged }}"
- name: "Generate kube-apiserver certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/kube-apiserver.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/kube-apiserver.key"
    csr_path: "{{ ssl_dir }}/kube-apiserver.csr"
    ownca_path: "{{ ssl_dir }}/ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/ca.key"


- name: "Generate kube-apiserver-kubelet-client private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/kube-apiserver-kubelet-client.key"
    type: RSA
    size: 4096
- name: "Generate kube-apiserver-kubelet-client request"
  openssl_csr:
    path: "{{ ssl_dir }}/kube-apiserver-kubelet-client.csr"
    privatekey_path: "{{ ssl_dir }}/kube-apiserver-kubelet-client.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: system:masters
    common_name: kube-apiserver-kubelet-client
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
- name: "Generate kube-apiserver-kubelet-client certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/kube-apiserver-kubelet-client.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/kube-apiserver-kubelet-client.key"
    csr_path: "{{ ssl_dir }}/kube-apiserver-kubelet-client.csr"
    ownca_path: "{{ ssl_dir }}/ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/ca.key"


- name: "Generate proxy-client private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/proxy-client.key"
    type: RSA
    size: 4096
- name: "Generate proxy-client request"
  openssl_csr:
    path: "{{ ssl_dir }}/proxy-client.csr"
    privatekey_path: "{{ ssl_dir }}/proxy-client.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: aggregator
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
- name: "Generate proxy-client certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/proxy-client.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/proxy-client.key"
    csr_path: "{{ ssl_dir }}/proxy-client.csr"
    ownca_path: "{{ ssl_dir }}/ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/ca.key"


- name: "Generate kube-controller-manager private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/kube-controller-manager.key"
    type: RSA
    size: 4096
- name: "Generate kube-controller-manager request"
  openssl_csr:
    path: "{{ ssl_dir }}/kube-controller-manager.csr"
    privatekey_path: "{{ ssl_dir }}/kube-controller-manager.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: system:kube-controller-manager
    common_name: system:kube-controller-manager
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
- name: "Generate kube-controller-manager certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/kube-controller-manager.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/kube-controller-manager.key"
    csr_path: "{{ ssl_dir }}/kube-controller-manager.csr"
    ownca_path: "{{ ssl_dir }}/ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/ca.key"


- name: "Generate kube-scheduler private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/kube-scheduler.key"
    type: RSA
    size: 4096
- name: "Generate kube-scheduler request"
  openssl_csr:
    path: "{{ ssl_dir }}/kube-scheduler.csr"
    privatekey_path: "{{ ssl_dir }}/kube-scheduler.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: system:kube-scheduler
    common_name: system:kube-scheduler
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
- name: "Generate kube-scheduler certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/kube-scheduler.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/kube-scheduler.key"
    csr_path: "{{ ssl_dir }}/kube-scheduler.csr"
    ownca_path: "{{ ssl_dir }}/ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/ca.key"

- name: "Generate kube-proxy private key"
  openssl_privatekey:
    path: "{{ ssl_dir }}/kube-proxy.key"
    type: RSA
    size: 4096
- name: "Generate kube-proxy request"
  openssl_csr:
    path: "{{ ssl_dir }}/kube-proxy.csr"
    privatekey_path: "{{ ssl_dir }}/kube-proxy.key"
    use_common_name_for_san: no
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: k8sre
    common_name: system:kube-proxy
    key_usage_critical: yes
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
- name: "Generate kube-proxy certificate"
  openssl_certificate:
    path: "{{ ssl_dir }}/kube-proxy.pem"
    provider: ownca
    privatekey_path: "{{ ssl_dir }}/kube-proxy.key"
    csr_path: "{{ ssl_dir }}/kube-proxy.csr"
    ownca_path: "{{ ssl_dir }}/ca.pem"
    ownca_privatekey_path: "{{ ssl_dir }}/ca.key"

- stat:
    path: "{{ ssl_dir }}/token"
  register: token
- name: "生成bootstrap-token-id"
  when: not token.stat.exists
  shell: openssl rand -hex 3
  register: token_id
- name: "生成bootstrap-token-secret"
  when: not token.stat.exists
  shell: openssl rand -hex 8
  register: token_secret
- name: "创建bootstrap-token文件"
  when: not token.stat.exists
  blockinfile:
    path: "{{ ssl_dir }}/token"
    block: "{{ token_id.stdout }}.{{ token_secret.stdout }}"
    create: true

