    - name: restart sshd
      systemd:
         name: sshd
         state: restarted
         enabled: yes
    - name: restart chrony
      systemd:
         name: chrony
         state: restarted
         enabled: yes