- name: "创建kube目录"
  file:
    path: "/root/.kube"
    state: directory
- name: "拷贝kubeconfig文件"
  template:
    src: "kubelet.kubeconfig.j2"
    dest: "/root/.kube/config"
- name: "安装kubectl"
  get_url:
    url: "{{ download_url }}/kubectl"
    dest: /usr/bin/
  tags: install_kubectl
- name: "添加执行权限"
  file:
    dest: "/usr/bin/kubectl"
    mode: 0755
  tags: install_kubectl
- name: "添加命令自动补全"
  lineinfile:
    dest: "/etc/profile"
    line: "source <(kubectl completion bash)"
    state: present
- name: "安装pip"
  yum:
    name: python-pip
    state: present
- name: "配置pip源"
  copy:
    src: "pip.conf"
    dest: "/root/.pip/"
- name: "安装python k8s模块"
  pip:
    name: "{{ item }}"
    state: present
  with_items: 
    - kubernetes
    - openshift