- name: "安装etcd"
  yum:
    name: etcd
    state: installed
- name: "分发证书"
  copy:
    src: "{{ item.line }}"
    dest: "{{ kube_dir }}/ssl/"
  with_items:
    - {line: '{{ ssl_dir }}/etcd-ca.pem'}
    - {line: '{{ ssl_dir }}/etcd-server.pem'}
    - {line: '{{ ssl_dir }}/etcd-server.key'}
    - {line: '{{ ssl_dir }}/etcd-client.pem'}
    - {line: '{{ ssl_dir }}/etcd-client.key'}
    - {line: '{{ ssl_dir }}/etcd-peer.pem'}
    - {line: '{{ ssl_dir }}/etcd-peer.key'}
  tags: dis_certs
- name: "拷贝etcd配置文件"
  template:
    src: "etcd.conf.j2"
    dest: "/etc/etcd/etcd.conf"
- name: "拷贝etcd service文件"
  template:
    src: "etcd.service.j2"
    dest: "/usr/lib/systemd/system/etcd.service"
- name: "创建etcd数据目录权限"
  file:
    path: "{{ kube_data_dir }}/etcd"
    owner: etcd
    group: etcd
    state: directory
- name: "启动服务"
  systemd:
    name: etcd
    daemon_reload: yes
    enabled: yes
    state: restarted
  tags: restart_etcd