- name: "安装依赖"
  yum:
    name: "{{ item.line }}"
    state: installed
  with_items:
    - {line: 'libnetfilter_conntrack-devel'}
    - {line: 'libnetfilter_conntrack'}
    - {line: 'conntrack-tools'}
    - {line: 'socat'}
    - {line: 'ipvsadm'}
- name: "添加kubernetes软件源"
  yum_repository:
    file: kubernetes
    name: "kubernetes"
    description: "kubernetes Repo"
    baseurl: "http://mirrors.cloud.aliyuncs.com/kubernetes/yum/repos/kubernetes-el7-x86_64 \n https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64"
    gpgkey: "http://mirrors.cloud.aliyuncs.com/kubernetes/yum/doc/yum-key.gpg \n https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg \n http://mirrors.cloud.aliyuncs.com/kubernetes/yum/doc/rpm-package-key.gpg \n https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg"
    gpgcheck: yes
    enabled: yes
  tags: kube_repo
- name: "安装kubelet"
  yum:
    update_cache: yes
    enablerepo: kubernetes
    name: 'kubelet{% if kubernetes_version is defined and kubernetes_version != ""  %}-{{ kubernetes_version }}{% endif %}'
    state: installed
- name: "创建kube目录"
  file:
    path: "{{ item.line }}"
    state: directory
    mode: '0755'
  with_items:
    - {line: "/etc/kubernetes/pki"}
    - {line: "/etc/kubernetes/manifests"}
    - {line: "/usr/lib/systemd/system/kubelet.service.d/"}
  tags: dir
- name: "分发node证书文件"
  copy:
    src: "{{ item.line }}"
    dest: "/etc/kubernetes/pki/"
  with_items:
    - {line: "{{ ssl_dir }}/ca.pem"}
    - {line: "{{ ssl_dir }}/ca.key"}
    - {line: "{{ ssl_dir }}/kube-proxy.pem"}
    - {line: "{{ ssl_dir }}/kube-proxy.key"}
    - {line: "{{ ssl_dir }}/token"}
- name: "读取当前bootstrap-token-id"
  shell: cat /etc/kubernetes/pki/token | grep -v "^#" | awk -F '.' '{print $1}'
  register: token_id
- name: "读取当前bootstrap-token-secret"
  shell: cat /etc/kubernetes/pki/token | grep -v "^#" | awk -F '.' '{print $2}'
  register: token_secret
- name: "生成kubelet配置文件"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "bootstrap.kubeconfig.j2",dest: "/etc/kubernetes/bootstrap.kubeconfig" }
    - {src: "kube-proxy.kubeconfig.j2",dest: "/etc/kubernetes/kube-proxy.kubeconfig" }
    - {src: "kubelet.yml.j2",dest: "/etc/kubernetes/kubelet.yml" }
    - {src: "10-kubelet.conf.j2",dest: "/usr/lib/systemd/system/kubelet.service.d/10-kubelet.conf" }
  notify:
    - restart kubelet
- name: "删除bootstrap-token文件"
  file:
    path: "/etc/kubernetes/pki/token"
    state: absent
    