- name: "下载calico部署文件"
  get_url:
    url: "https://docs.projectcalico.org/v3.8/manifests/calico-etcd.yaml"
    dest: /root/
- name: "拷贝calico-etcd证书"
  copy:
    src: "{{ item.line }}"
    dest: "{{ kube_dir }}/ssl/"
  with_items:
    - {line: '{{ ssl_dir }}/ca.pem'}
    - {line: '{{ ssl_dir }}/etcd-calico.pem'}
    - {line: '{{ ssl_dir }}/etcd-calico.key'}
- name: "获取etcd-calico.key证书内容"
  shell: cat {{ kube_dir }}/ssl/etcd-calico.key | base64 | tr -d '\n'
  register: calico_key
- debug:
    msg: "{{ calico_key }}"
- name: "获取etcd-calico.pem证书内容"
  shell: cat {{ kube_dir }}/ssl/etcd-calico.pem | base64 | tr -d '\n'
  register: calico_pem
- debug:
    msg: "{{ calico_pem }}"
- name: "获取ca.pem证书内容"
  shell: cat {{ kube_dir }}/ssl/ca.pem | base64 | tr -d '\n'
  register: ca_pem
- debug:
    msg: "{{ ca_pem }}"
- name: "修改calico-etcd部署文件"
  lineinfile:
    dest: "/root/calico-etcd.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "typha_service_name:", line: "typha_service_name: "calico-typha"" }
    - { regexp: "192.168.0.0/16", line: "{{ pod_cluster_cidr }}" }