- name: "创建kubectl目录"
  file:
    path: "~/.kube"
    state: directory
- name: "安装kubectl"
  yum:
    update_cache: yes
    enablerepo: kubernetes
    name: 'kubectl{% if kubernetes_version is defined and kubernetes_version != ""  %}-{{ kubernetes_version }}{% endif %}'
    state: installed
- name: "添加命令自动补全"
  lineinfile:
    dest: "/etc/profile"
    line: "source <(kubectl completion bash)"
    state: present
- name: "分发master证书文件"
  copy:
    src: "{{ item.line }}"
    dest: "/etc/kubernetes/pki/"
  with_items:
    - {line: '{{ ssl_dir }}/ca.key'}
    - {line: '{{ ssl_dir }}/ca.pem'}
    - {line: '{{ ssl_dir }}/etcd-client.key'}
    - {line: '{{ ssl_dir }}/etcd-client.pem'}
    - {line: '{{ ssl_dir }}/kube-apiserver.key'}
    - {line: '{{ ssl_dir }}/kube-apiserver.pem'}
    - {line: '{{ ssl_dir }}/kube-apiserver-kubelet-client.key'}
    - {line: '{{ ssl_dir }}/kube-apiserver-kubelet-client.pem'}
    - {line: '{{ ssl_dir }}/kube-controller-manager.key'}
    - {line: '{{ ssl_dir }}/kube-controller-manager.pem'}
    - {line: '{{ ssl_dir }}/kube-scheduler.key'}
    - {line: '{{ ssl_dir }}/kube-scheduler.pem'}
    - {line: '{{ ssl_dir }}/proxy-client.key'}
    - {line: '{{ ssl_dir }}/proxy-client.pem'}
    - {line: '{{ ssl_dir }}/admin.key'}
    - {line: '{{ ssl_dir }}/admin.pem'}
  tags: dis_certs
- name: "分发kubeconfig"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "admin.kubeconfig.j2",dest: "~/.kube/config" }
    - {src: "kube-controller-manager.kubeconfig.j2",dest: "/etc/kubernetes/kube-controller-manager.kubeconfig" }
    - {src: "kube-scheduler.kubeconfig.j2",dest: "/etc/kubernetes/kube-scheduler.kubeconfig" }
    - {src: "kube-apiserver.yaml.j2",dest: "/etc/kubernetes/manifests/kube-apiserver.yaml" }
    - {src: "kube-controller-manager.yaml.j2",dest: "/etc/kubernetes/manifests/kube-controller-manager.yaml" }
    - {src: "kube-scheduler.yaml.j2",dest: "/etc/kubernetes/manifests/kube-scheduler.yaml" }
  notify:
    - restart kubelet
